### ISSUE TITLE
Incorrect constant 2^16

### ISSUE THREAD

**Issue by borysyuk** [ethereum934/eth-mimblewimble#4]
Hi,
You have used this validator
`require(pool.mmrWidths[root] + 4 < 66536, "This 16 bit MMR only contains 66535 items");`
in several places. 
In my opinion, the constant `66536` has to be replaced to 65536 because 65536 == 2^16
Thanks.

**Comment by wanseob** [comment]
Ooph what a mistake. Thanks @borysyuk  for your feedback gonna fix it soon!
